version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - ./app.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: golang_fiber
volumes:
  progresDB:
