basePath: /
definitions:
  models.BlogPost:
    properties:
      body:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
  models.CreateBlogPostSchema:
    properties:
      body:
        type: string
      description:
        type: string
      title:
        type: string
    required:
    - body
    - description
    - title
    type: object
host: 20.25.40.163:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blog-Post API
  version: "2.0"
paths:
  /api/blog-post:
    get:
      consumes:
      - application/json
      description: Get all exists blogPosts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BlogPost'
            type: array
      summary: get all exists blogPosts
      tags:
      - BlogPosts
    post:
      consumes:
      - application/json
      description: Create a new blogPost.
      parameters:
      - description: BlogPost
        in: body
        name: blogPost
        required: true
        schema:
          $ref: '#/definitions/models.CreateBlogPostSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: create a new blogPost
      tags:
      - BlogPosts
  /api/blog-post/{id}:
    delete:
      consumes:
      - application/json
      description: Delete blogPost by given ID.
      parameters:
      - description: blogPostId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: delete blogPost by given ID
      tags:
      - BlogPosts
    get:
      consumes:
      - application/json
      description: Get blogPosts by given ID.
      parameters:
      - description: blogPostId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: get blogPosts by given ID
      tags:
      - BlogPosts
    patch:
      consumes:
      - application/json
      description: Update blogPost.
      parameters:
      - description: blogPostId
        in: path
        name: id
        required: true
        type: string
      - description: BlogPost
        in: body
        name: blogPost
        required: true
        schema:
          $ref: '#/definitions/models.CreateBlogPostSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: update blogPost
      tags:
      - BlogPosts
schemes:
- http
swagger: "2.0"
