basePath: /
definitions:
  models.BlogPost:
    properties:
      body:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blog-Post API
  version: "2.0"
paths:
  /api/blog-post:
    get:
      consumes:
      - application/json
      description: Get all exists blogPosts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BlogPost'
            type: array
      summary: get all exists blogPosts
    patch:
      consumes:
      - application/json
      description: Update blogPost.
      parameters:
      - description: BlogPost ID
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Content
        in: body
        name: content
        required: true
        schema:
          type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: update blogPost
    post:
      consumes:
      - application/json
      description: Create a new blogPost.
      parameters:
      - description: Title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Content
        in: body
        name: content
        required: true
        schema:
          type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: create a new blogPost
  /api/blog-post/{id}:
    delete:
      consumes:
      - application/json
      description: Delete blogPost by given ID.
      parameters:
      - description: blogPostId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: delete blogPost by given ID
    get:
      consumes:
      - application/json
      description: Get blogPosts by given ID.
      parameters:
      - description: blogPostId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogPost'
      summary: get blogPosts by given ID
schemes:
- http
swagger: "2.0"
